env:
  browser: true
  es2021: true

extends:
  airbnb-base/legacy

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules: {
      "no-console": "off"
    }
    {
    "prefer-destructuring": ["error", {"object": true, "array": false}]
  }
